### ISSUE TITLE
infra(integration): Hello World action 추가

### ISSUE THREAD

**Issue by kimseungbin** [docker-seminar/docker-basics#26]
# 기능

- trigger 에 따라 다른 Hello World 를 출력하는 Action 작성

예시:

```YAML
jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Step for Push
        if: ${{ github.event_name == 'push' }}
        run: echo "This workflow was triggered by a push."

      - name: Step for Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This workflow was triggered by a pull request."

      - name: Step for Manual Trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "This workflow was triggered manually."
```

# 목적

- 다양한 Action Trigger 체험
