### ISSUE TITLE
infra(docs): 이슈 템플릿

### ISSUE THREAD

**Issue by kimseungbin** [docker-seminar/docker-basics#3]
# GitHub Issue 란?

- https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

# Issue Template 템플릿 이란?

[GitHub Docs: About issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

GitHub 자체 번역 수준이 처참하니 번역이 필요한 경우 그냥 브라우저의 번역 기능 이용할 것을 추천...

# 예시

(민규 예시)

```YAML
---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

# 기능 명세

요청한 기능 명세를 명확하고 간결하게 작성하시오.

- 해당 기능이 어떤 역할을 수행하는가?
- 해당 기능이 어떻게 작동하는가?
- 구현이 어려운 경우 차선택이 있는가?

### 작업 상세 내용
- [ ] 해야 할 작업 1  
- [ ] 해야 할 작업 2  
- [ ] 기타 필요한 작업
- [ ] 

# 해당 기능 필요성

기능 요청의 중요성을 상세하게 작성하시오. 

- 해당 기능은 어떤 문제를 다루는가?
- 해당 기능은 프로젝트 목표나 사용자의 요구사항과 부합하는가?
- 해당 기능을 구현하였을 경우 어떤 이점을 가져오는가?

# 추가 내용 (선택 사항)

기능 요청을 이해하기 위한 추가 정보를 작성하시오.

- 해당 기능이 기존에 사용되는 경우가 있는가?
- 설명을 위한 다른 다이어그램 혹은 모형이 있는가?
- 해당 기능을 구현할 경우 발생하는 잠재적 문제나 고려 사항이 있는가?
- 해당 기능이 기존 기능에 어떤 영향을 미치는가?
```

(승빈 예시)

```YAML
# .github/ISSUE_TEMPLATE/feature_request.md
---
name: Feature Request
about: Suggest a new feature or improvement
title: 'Feat: [enter feature summary]'
labels: enhancement, minor
assignees: kimseungbin  # or assign another default user

---

# Feature Description

Please provide a clear and concise description of the feature you'd like to request. Consider including:

- What problem does this feature solve?
- How would you like this feature to work?
- Are there any alternatives you've considered?

# Why is this feature needed?

Please explain the importance of this feature request:

- What specific problem or pain point does this feature address?
- How does this feature align with the project's goals or user needs?
- What are the expected benefits or improvements after implementing this feature?

# Additional Context

Please provide any additional information that could help us understand and evaluate your feature request:

- Are there any specific use cases or scenarios where this feature would be particularly useful?
- Do you have any mockups, diagrams, or examples from other projects that illustrate your idea?
- Are there any potential challenges or considerations we should be aware of when implementing this feature?
- How does this feature request related to or impact existing functionality?

Feel free to attach screenshots, links or any other relevant resources.
```

기타 템플릿은 검색 참조
![Image](https://github.com/user-attachments/assets/2ce20bd1-1167-4f83-a315-ed7e5570bf1a)

## OO사이트의 예시

# Repository 에 추가하는 방법

1. 하나
  ```yaml
  foo:
    bar:
      - baz
  ```

2. 둘
